### ISSUE TITLE
[question] - Can I monitor Job status event, like "Completed"

### ISSUE THREAD

**Issue by dpeer6** [flant/shell-operator#191]
I run few batch general processes as jobs (kind: Job) on my k8s cluster, and like to trigger based on event, for example when it is marked as "Completed". Is it doable?

**Comment by zuzzas** [comment]
Sure. Something like this should work:

```yaml
configVersion: v1
kubernetes:
- name: completed_jobs
  apiVersion: batch/v1
  kind: Job
  namespace:
    nameSelector:
      matchNames: [your-namespace]
  executeHookOnSynchronization: false
  jqFilter: ".status.completionTime"
```
