### ISSUE TITLE
Annotation Event Trigger Not Working

### ISSUE THREAD

**Issue by infinitydon** [flant/shell-operator#217]
Hi,

Please I am trying to watch events based on annotations but so far I can't see any traces in the logs if it is working or not.

Hook script:

```
if [[ $1 == "--config" ]] ; then
  cat <<EOF
configVersion: v1
kubernetes:
- name: OnCreatePod
  apiVersion: v1
  kind: Pod
  executeHookOnEvent:
  - Added
  - Deleted
EOF
else
  # ignore Synchronization for simplicity
  type=$(jq -r '.[0].type' $BINDING_CONTEXT_PATH)
  if [[ $type == "Synchronization" ]] ; then
    echo Got Synchronization event
    exit 0
  fi

  if [[ $type == "Event" ]] ; then
  resourceEvent=$(jq -r '.[0].watchEvent' $BINDING_CONTEXT_PATH)
  resourceName=$(jq -r '.[0].object.metadata.name' $BINDING_CONTEXT_PATH)
  resourceNameSpace=$(jq -r '.[0].object.metadata.namespace' $BINDING_CONTEXT_PATH)
  checkAnnotation=$(jq -r '.[0].object.metadata.annotations' $BINDING_CONTEXT_PATH | grep -w service-name)

        if [[ -z "${checkAnnotation}"]];  then
                      if [[ $resourceEvent == "Added" ]] ; then
                          echo "Pod with service name annotation has been created"
                      else
                          echo "Pod with service name annotation has been deleted"
                      fi
        fi
  fi
fi
```

RBAC:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotations-service-acct
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: annotations-monitor-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: annotations-monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: annotations-monitor-pods
subjects:
  - kind: ServiceAccount
    name: annotations-service-acct
    namespace: kube-system
```

Logs from the shell-operator POD:

```
{"level":"info","msg":"shell-operator master-9c5f0a6c-ubuntu-2020.11.18_20:08:25","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Listen on 0.0.0.0:9115","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_live_ticks","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric histogram shell_operator_tasks_queue_action_duration_seconds","operator.component":"metricsStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric gauge shell_operator_tasks_queue_length","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric gauge shell_operator_kube_snapshot_objects","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric gauge shell_operator_kube_snapshot_bytes","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric histogram shell_operator_kube_jq_filter_duration_seconds","operator.component":"metricsStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric histogram shell_operator_kube_event_duration_seconds","operator.component":"metricsStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric gauge shell_operator_hook_enable_kubernetes_bindings_seconds","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_hook_enable_kubernetes_bindings_errors_total","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric gauge shell_operator_hook_enable_kubernetes_bindings_success","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric histogram shell_operator_hook_run_seconds","operator.component":"metricsStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_hook_run_errors_total","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_hook_run_allowed_errors_total","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_hook_run_success_total","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_task_wait_in_queue_seconds_total","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Hooks dir: /hooks","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Use temporary dir: /tmp/shell-operator","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Debug endpoint listen on /var/run/shell-operator/debug.socket","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric histogram shell_operator_kubernetes_client_request_latency_seconds","operator.component":"metricsStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Create metric counter shell_operator_kubernetes_client_request_result_total","operator.component":"metricStorage","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Kubernetes client is configured successfully with 'out-of-cluster' config","operator.component":"KubernetesAPIClient","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"Initialize hooks manager. Search for and load all hooks.","time":"2020-12-04T17:33:03Z"}
{"level":"info","msg":"start shell-operator","time":"2020-12-04T17:33:03Z"}
```

Any idea why this is not working?

**Comment by diafour** [comment]
Hello!

```
- name: OnCreatePod
  apiVersion: v1
  kind: Pod
  executeHookOnEvent:
  - Added
  - Deleted
```

The problem is that the hook with this configuration receives only Pods that created or deleted after the shell-operator startup.

I see these issues:
- The hook is executed with a "Synchronization" event to handle all existed objects. But "Synchronization is ignored for simplicity". So, no messages about existed objects.
- There is no `Modified` event in executeHookOnEvent. So, no messages about annotation changes on existed objects.
- `0` index in jq expressions ignores the fact that the binding context can have many items. See [this comment](https://github.com/flant/shell-operator/issues/192#issuecomment-666317662)
