### ISSUE TITLE
fullObjectInSnapshot documentation bug

### ISSUE THREAD

**Issue by teejaded** [flant/shell-operator#240]
**Expected behavior (what you expected to happen)**:

I expected `kubernetes.fullObjectInSnapshot: false` to give me a jqFilter'ed list of data. I saw this is HOOKS.md.

```yaml
configVersion: v1
kubernetes:
- name: "Monitor pods in cache tier"
  apiVersion: v1
  kind: Pod  # required
  executeHookOnEvent: [ "Added", "Modified", "Deleted" ]
  executeHookOnSynchronization: true|false # default is true
  fullObjectInSnapshot: true|false # default is true
```

**Actual behavior (what actually happened)**:

Error message on hook config load:

`kubernetes.fullObjectInSnapshot is a forbidden property`

I don't see that property listed here so I guess it's just a documentation bug.

https://github.com/flant/shell-operator/blob/master/pkg/hook/hook_config.go#L84-L104

**Environment**:
- Shell-operator version: flant/shell-operator:latest-alpine3.12  (shell-operator master-9c5f0a6c-alpine3.12-2020.11.18_20:08:27)
- Kubernetes version: v1.16.15
- Installation type (kubectl apply, helm chart, etc.): kubectl apply
