### ISSUE TITLE
Kubernetes Object Manipulation action `CreateIfNotExists` is document but is unimplemented

### ISSUE THREAD

**Issue by nairb774** [flant/shell-operator#278]
[Modifying Kubernetes objects](https://github.com/flant/shell-operator/blob/v1.0.0/KUBERNETES.md) documents the operation `CreateIfNotExists` but attempting to use it causes [validation to fail](https://github.com/flant/shell-operator/blob/master/pkg/kube/object_patch/validation.go#L75) as it [doesn't look to be implemented](https://github.com/flant/shell-operator/blob/v1.0.0/pkg/kube/object_patch/patch.go#L69-L72).

**Actual behavior (what actually happened)**:

Related log output:

```
ERRO[0125] Hook failed. Will retry after delay. Failed count is 2. Error: 88 errors occurred:
        * can't validate document:
object:
  apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      managed-namespace: vertical-pod-autoscaler
      shell-operator: 006-flux-provision
    name: deploy-ns-vertical-pod-autoscaler
    namespace: flux-system
    ownerReferences:
    - apiVersion: v1
      kind: Namespace
      name: vertical-pod-autoscaler
      uid: 7ba6e4ae-2ba4-45da-9750-19075adc6ae6
operation: CreateIfNotExists

        * "" must validate one and only one schema (oneOf). Found none valid
        * operation should be one of [Create CreateOrUpdate]
        * "" must validate all the schemas (allOf)
  binding=kubernetes event=kubernetes hook=006-flux-provision queue=main task=HookRun
```

**Environment**:
- Shell-operator version: v1.0.0

**Anything else we should know?**:

Thanks for this fantastic utility!
