### ISSUE TITLE
[Proposal] Lazy quickstart guide

### ISSUE THREAD

**Issue by mac2000** [flant/shell-operator#305]
Seems like quickstart is not really so quick, we need to do so many things, especially those about docker registries and so on

Will be so nice to have something like this one:

**oper.yml**

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: oper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oper
  namespace: oper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oper
  namespace: oper
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oper
  namespace: oper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oper
subjects:
- kind: ServiceAccount
  name: oper
  namespace: oper
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oper
  namespace: oper
data:
  oper.sh: |
    #!/usr/bin/env bash

    if [[ $1 == "--config" ]]
    then
      echo '
      configVersion: v1
      kubernetes:
      - apiVersion: v1
        kind: Pod
        executeHookOnEvent: ["Added"]
      '
    else
      podName=$(jq -r .[0].object.metadata.name $BINDING_CONTEXT_PATH)
      echo "Pod '${podName}' added"
    fi    
---
apiVersion: v1
kind: Pod
metadata:
  name: oper
  namespace: oper
spec:
  serviceAccountName: oper
  volumes:
  - name: oper
    configMap:
      name: oper
      defaultMode: 0755
  containers:
  - name: oper
    image: flant/shell-operator:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: oper
      subPath: oper.sh
      mountPath: /hooks/oper.sh
```

with such an example, all we needed to do is:

```bash
kubectl apply -f oper.yml
kubectl -n oper logs oper -f
kubectl delete -f oper.yml
```
