### ISSUE TITLE
Consistency of reconciliation and onKubernetesEvents

### ISSUE THREAD

**Issue by distol** [flant/shell-operator#42]
The most natural way is to run initial reconciliation in onStartup and than follow all the changes using onKubernetesEvents hooks. But to do that there should be the guarantee, that:
1. No events will be missed between onStartup and creation of informers for onKubernetesEvents hooks.
2. No onKubernetesEvents hooks will be executed until onStartup is finished. We don't want to follow changes until initial reconciliation is completed. But if we receive the event for the change that already processed during reconciliation stage – that's not a problem, because all the actions in onKubernetesEvents hooks should be idempotent.

To do that, during hooks configuration stage we shall do the following:
1. Read all the hooks configuration.
2. Fill the queue with onStartup hooks (but not run them yet).
3. Create informers (they will add new tasks after onStartup).
4. Start running the queue.

P.S. We shall document described approach as recommended!

**Comment by distol** [comment]
Result of brief discussion with @diafour.

We are going to:
1. Introduce types for onKubernetesEvents binding contexts.
2. Add `type: Reconcile` which will contain the whole list of resources.
3. Add `resource` (whole object JSON) and `resourceFilterResult` (result of `jqFilter`).
4. Also, deprecate `resourceEvent` in favor of `event`
5. (?) Add `reconcilePeriod` to onKubernetesEvents config

Example of binding context, we are going to implement:
```
- binding: watch-pods
   type: Event
   event: Add | Update | Delete
   resourceEvent: add | update | delete        # deprecation, remove from the docs
   resourceNamespace: my-ns
   resourceKind: Pod
   resourceName: blah-blah
   resource: {}
   resourceFilterResult: {}
- binding: watch-pods
   type: Reconcile
   resources:
   - resourceNamespace: my-ns
      resourceKind: Pod
      resourceName: blah-blah
      resource: {}
      resourceFilterResult: {}
   - resourceNamespace: my-ns
      resourceKind: Pod
      resourceName: blah-blah
      resource: {}
      resourceFilterResult: {}
```

Backward compatibility strategy:
- introduce internal-only setting for onKubernetesEvent bindings: `reconcile: bool`
- v0 (legacy version): don't execute hooks for `type: Reconcile`
- v1: do the stuff
